[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_mysql", "php83Extensions.gd", "php83Extensions.mbstring", "php83Extensions.zip", "php83Extensions.bcmath", "php83Extensions.intl", "php83Extensions.curl", "composer"]

[phases.install]
cmds = ["composer install --no-interaction --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["php artisan key:generate --show", "php artisan config:cache", "php artisan route:cache", "php artisan migrate --force"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
