[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_mysql", "php83Extensions.gd", "php83Extensions.mbstring", "php83Extensions.zip", "php83Extensions.bcmath", "php83Extensions.intl", "php83Extensions.curl", "php83Extensions.exif", "composer"]

[phases.install]
cmds = ["composer install --no-interaction --no-dev --optimize-autoloader"]

[phases.build]
cmds = []

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
